export type ContentSection = { heading?: string; paragraphs: string[] };
export const storeContent: Record<string, { title: string; sections: ContentSection[] }> = {
  'shipping-policy': { title: 'Shipping policy', sections: [{ paragraphs: [
    'Your order journey begins the time you click “Place Order”. Once we receive your order, then it becomes our responsibility to send you a quick confirmation to your registered mobile number or email.',
    'And when your order is ready for shipment, we will keep you updated with a dispatch notification or shipping notice.',
    'For Cash on Delivery (COD) orders, we may ask you to confirm your order via the message or link that was sent to your registered contact details. After confirmed, our team will get your order ready for dispatch.',
    'The moment your package is handed over to our delivery partner, they safely deliver it to the address you provided while placing your order. If they need any help while finding the address of the delivery, they may get in touch with you.',
    'Also, We usually dispatch orders within 2-7 working days.',
    'Note* At present, Glownari ships only within India. We hope to bring your favourite (faves) products to more destinations soon.',
  ] }] },
  'privacy-policy': { title: 'Privacy policy', sections: [
    { paragraphs: ['All the information which you provide us is more than a collection of numbers, names and clicks.', 'It’s an idea regarding what we collect from your private data, why we need it and what we do to keep it safe and secure, because Glownari believes that your privacy begins with honesty.'] },
    { heading: 'What We Collect', paragraphs: ['First, we collect information that you share with us directly. Like: your name, phone number, email address or other details which you submit via our website.', 'Second, we may also automatically collect the basic technical information, such as: your browser (Chrome, Firefox, Safari or Edge), IP address, device type and how you connect with our website.'] },
    { heading: 'Why We Need It', paragraphs: ['We need it to make our services and website work better for you.', 'The information we collect from your support helps us respond to your queries, increase your experience and keep our website secure.'] },
    { heading: 'What We Do To Keep It Safe and Secure', paragraphs: ['We take reasonable organizational and technical measures that are created to protect personal information against misuse, unauthorized access, disclosure, alteration or destruction.'] },
    { heading: 'Privacy Policy Updates', paragraphs: ['This “privacy policy” is updated from time to time to showcase changes to our website, services or legal requirements. That’s why it’s important to thoroughly read this page regularly for the latest information about how your information is used, collected and protected. The updated version of this policy will always be posted on this page.'] },
    { heading: 'Email Updates & Marketing', paragraphs: ['By subscribing to our newsletter, you are given us a green flag on agreeing to receive emails that contain product promotions, updates and other relevant information.', 'Note* You can unsubscribe from these communications at any time.'] },
  ] },
  terms: { title: 'Term of service', sections: [
    { paragraphs: ['Every relationship works better when there is space of clarity. These “terms of service” are here for exactly that, to make the experience between you and Glownari transparent and simple from the start.', 'When you explore our website, create an account or place an order, you agree to the terms below.'] },
    { heading: 'The Information We Deliver', paragraphs: ['With full understanding and an active mind, we prepare the pricing, images, information and descriptions for you to find on Glownari.', 'Prices, information and availability may change as our services and products evolve.'] },
    { heading: 'Order & Payments', paragraphs: ['Kindly take a moment to thoroughly go through your order details before completing your purchase. Accurate delivery and contact information helps us to deliver your order in the correct destination without any delay.', 'i) Orders depend on confirmation and availability. We can cancel an order if the information shared by us is incorrect or the service is being misused.', 'ii) Payments are completed securely through our payment service partners. Glownari does not store your debit or credit card information on its own servers.'] },
    { heading: 'Return & Deliver', paragraphs: ['We aim to return and deliver your orders within 2–7 business days after confirmation.'] },
    { heading: 'Refund Policy', paragraphs: ['Our Refund Policy offers complete information about eligible refunds, cancellations and replacements. Please look over the policy for full details.'] },
    { heading: 'Accounts', paragraphs: ['While creating an account with Glownari, please make sure that your login information is safe and the details in your account are accurate and updated. You are in charge of keeping your account secure and for any actions that are taken through your account.'] },
    { heading: 'Creative Rights', paragraphs: ['Everything that we created including our logo, name, photos, graphics, content and designs, belongs to the Glownari and is protected by applicable intellectual property rights (IPR).', 'You are invited to view and explore our content, but please do not share, copy, change or use it for business purposes without our written consent.'] },
    { heading: 'Privacy', paragraphs: ['Any information that you have shared with us is controlled according to our Privacy Policy. It describes how we use the information, what information we collect, and how we work to keep your information private and secure.'] },
  ] },
  faqs: { title: 'FAQs', sections: [
    { heading: 'How long does Glownari take to deliver orders?', paragraphs: ['Glonari takes only 2–7 working days to deliver orders.'] },
    { heading: 'Where can I buy stylish jewellery online?', paragraphs: ['You can buy stylish jewellery at “Glownari”. Visit the website and check out the iconic designs that are designed for your happiness.'] },
    { heading: 'How do I buy jewellery online from Glownari?', paragraphs: ['You can buy jewellery online from Glownari, while choosing your preferred earrings or ring, explore the product details and sizing wherever are relevant, add your preference to the cart and complete your order through the process of checkout.'] },
    { heading: 'How can I contact Glownari about my jewellery order?', paragraphs: ['You can directly contact the Glownari support team through the provided contact details that are shared on our website, feel free to ask your questions about orders, products, delivery, sizing, returns or other concerns.'] },
    { heading: 'Can I wear Glownari jewellery for both casual and formal looks?', paragraphs: ['Yes, you can wear glownari jewellery for both casual and formal looks. You just need to select the elegant or simple designs for everyday and bold or statement pieces for special occasions.'] },
    { heading: 'Is the jewellery exactly as shown in the pictures?', paragraphs: ['Yes, we truly focus on showing products that match their displayed pictures.'] },
  ] },
  'about-us': { title: 'About Us', sections: [
    { heading: 'Hello, beautiful!', paragraphs: ['Can we tell you a small secret?', "It’s about every piece of jewellery that has a story waiting to happen. Maybe yours start with a ring you couldn't stop imagining, earrings you often fell in love with, or a tiny sparkle you added to your collection just because you deserved it.", 'At Glownari, we bring those little pieces for you. Pieces that glow into a part of your feelings, your days and in the end, your story.'] },
    { heading: 'Why Stop at Glownari ?', paragraphs: ['1. Timeless Designs:: We keep an eye on what’s trending and provide you with jewellery that helps you stay stylish without losing your signature charm.', '2. Reasonable Prices: Glownari comes up with fashionable jewellery at affordable prices and brings it easy to refresh your collection with fresh pieces.', '3. Wide Range: From “daily used” earrings to “statement rings”, we are here to deliver you different styles that look good with special occasions and tastes.', '4. Easy to Express: Our pieces are presented to pair gracefully with special-occasion and everyday outfits.'] },
  ] },
};
